### ISSUE TITLE
Documentation not understandable for vim beginners

### ISSUE THREAD

**Issue by RedX2501** [nvie/vim-togglemouse#3]
The sentence "If you don't want to use the <F12> key for mouse toggling, simply remap it to another key." is a little bit confusing to beginners.

What does "simply remap" mean?

I for example have F12 set to togglepaste and would like to have F11 set to togglemouse but so fall all my attempts have failed.

What is the correct form to remap it in .vimrc?

**Comment by nvie** [comment]
Sorry about that—I should really avoid the term "simply" in docs, thanks for calling it out.

The correct lines to include in your `.vimrc` would be:

``` viml
noremap <F11> :call <SID>ToggleMouse()<CR>
inoremap <F11> <Esc>:call <SID>ToggleMouse()<CR>a
```

**Comment by RedX2501** [comment]
I'm using it with vundle. Must those lines go before or after the vundle loading?
It seems your suggestion did not work as i tried that before.
